### PR TITLE
add whitelist_testing.sh

### PR DESCRIPTION
**Pull request by giovino**
script to test whitelisting. associated to https://github.com/csirtgadgets/p5-cif-sdk/issues/30

### CODE REVIEW

**Comment by wesyoung** [comment]
since we presumably have ~/.cif.yml setup, do we even need an "$EVERYONETOKEN" ?

**Comment by giovino** [comment]
Not really.. i thought about removing it all together.. then decided to leave it as it would prevent someone from accidentally running it. I am not married to the idea of specifying it.

**Comment by wesyoung** [comment]
problem is, as is, if we leave it the script won't run.. so we prob either have to remove it OR have bash check for an ENV override?

if you want to protect against "accidental" run, i'd remove it, check for a specifically set ENV var to run, and spit out an error if that ENV var (CIF_TEST=1 or something) is not set...

**Comment by giovino** [comment]
"problem is, as is, if we leave it the script won't run.."

how is this any different than group_testing.sh? are you thinking you want to call this programmatically? (travisci)?

**Comment by wesyoung** [comment]
i think i overlooked it wrt group testing.

what if we just generated the token automatically in the script, then piled in the removal commands at the end (same with data, calling the curl commands from src/elasticsearch/makefile.am). something like:

something like we did here:

https://github.com/collectiveintel/cif-v1/blob/master/cif-test-framework/bin/cif_test_framework#L105

1. create new key
2. run tests
3. remove data
4. remove key

ideally i want to push towards "doing this in travis", whether we get there sooner than later, where its a quick win i'd like to move in that direction...

**Pull request merged**
