### PR TITLE
Added a new command-line parameter to cif-tokens: --storage-host

### PR DESCRIPTION
**Pull request by shatlovsky**
In conjunction with --storage, it allows to specify remote storage
host/port

### CODE REVIEW

**Comment by wesyoung** [comment]
ty! i'm gonna tie this to #176 to double check a few things and combine in some other stuff... hopefully this will get pulled into alpha.18

**Comment by shatlovsky** [comment]
thanks! I'm actually working on the task as in #176, hopefully will be done by Wednesday evening.

**Comment by wesyoung** [comment]
rock on, thanks!

**Comment by wesyoung** [comment]
can you do me a favor and re-pull this one against the develop branch? thanks!

**Comment by shatlovsky** [comment]
no problem, pulled the changes to the develop branch

**Pull request closed without merging**
